name: Release Nuget package
on:
  release:
    types: [published]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '5.x' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Dotnet ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Release
        run: |
          cd src
          msbuild /r ApiVideo.csproj
          msbuild -t:pack
          cd bin/Debug
          nuget push `ls ApiVideo*nupkg` -Source nuget.org -ApiKey $NUGET_KEY -NonInteractive
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
